### ISSUE TITLE
query only in a given bbox?

### ISSUE THREAD

**Issue by pcace** [geostyler/geostyler-wfs-parser#451]
Hi 
is it possible to add a way to only get data from wfs server within a certain bbox? 

Cheers

**Comment by jansule** [comment]
Yes, you can add a `bbox: 'a1,b1,a2,b2,CRS'` property to the `requestParams` argument of `readData()`.

**Comment by KaiVolland** [comment]
Can this bei closed?

**Comment by pcace** [comment]
yes thanks! works as expected!
