### ISSUE TITLE
outputFormat application/geo+json possible?

### ISSUE THREAD

**Issue by pcace** [geostyler/geostyler-wfs-parser#452]
Hi there, is there any quick way to make it possible to be able to use servers with only outputFormat=application/geo+json enabled?

Thanks a lot!

**Comment by jansule** [comment]
It looks like we are currently hardcoding the outputFormat to `application/json` (see https://github.com/geostyler/geostyler-wfs-parser/blob/master/src/WfsDataParser.ts#L164).

From my side, it would be ok to make this configurable.

Are you planning on providing a PR for this?

**Comment by pcace** [comment]
Hi, i currently use my own simple fetch() for the specific usecase i have here, so currently no :/
